spring.application.name=springai-embeddings-vector-rag-demo-1

# Core Google GenAI properties
spring.ai.google.genai.api-key=YOUR_GOOGLE_API_KEY
spring.ai.google.genai.project-id=gen-lang-client-0730005632
spring.ai.google.genai.location=us-central1
spring.ai.google.genai.chat.options.model=gemini-3.6-flash

# Embedding specific properties
spring.ai.google.genai.embedding.api-key=YOUR_GOOGLE_API_KEY
spring.ai.google.genai.embedding.project-id=gen-lang-client-0730005632
spring.ai.google.genai.embedding.location=us-central1
spring.ai.google.genai.embedding.options.model=text-embedding-004